name: Build, Deploy, and Run Docker Image on EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/bot:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/bot:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy and run Docker container on EC2
        run: |
          echo ${{ secrets.SSH_PRIVATE_KEY }} > private_key && chmod 600 private_key

          ssh -o StrictHostKeyChecking=no -i private_key ec2-user@${{ secrets.EC2_HOST }} '

            docker pull ${{ secrets.DOCKER_USERNAME }}/bot:latest
            docker stop bot || true
            docker rm bot || true
            docker run -d --name bot -p 80:80 ${{ secrets.DOCKER_USERNAME }}/bot:latest
          '
